# Generated by Django 5.0 on 2023-12-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpname', models.CharField(max_length=100)),
                ('dpcode', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
