# Generated by Django 5.0 on 2024-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_employee',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation_employee',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
